### ISSUE TITLE
La función para leer el estado de un led modifica el estado del puerto

### ISSUE THREAD

**Issue by evolentini** [germanCardozoE/testingDeSoftwareEmbebido#3]
La función hace una asignación sobre el contenido del puerto, y por lo tanto lo cambia. 

https://github.com/germanCardozoE/testingDeSoftwareEmbebido/blob/0edc6d1971e93a1f7cec83fb072484a5e6803c3f/TP_ceedling/leds/src/leds.c#L40

Una prueba que mostraría el error sería la siguiente:

```c
void test_TurnOnAndOffManyLed(void){
   Led_TurnOn(LED);
   Led_Read(4);   
   TEST_ASSERT_EQUAL_HEX16(1 << (LED-1),ledsVirtuales); 
}
```

**Comment by evolentini** [comment]
Este error no se corrigió.

**Comment by germanCardozoE** [comment]
En cuanto a esta corrección sigo sin interpretarla.
No entiendo como escribir un led pero leer otro es correcto, pero leer el
led escrito es incorrecto.
¿Si no lo escribo o limpio previamente como se que debo esperar leer?

**Comment by evolentini** [comment]
German, te vuelvo a repetir que tenes un error en el código de la función: estas usando `&=` y eso modifica el estado de todos los otros leds. Por eso te digo que la prueba propuesta no pasaría, porque te estaría mostrando el error que tenes en la función.
