### ISSUE TITLE
El control de limites debe hacerse internamente en las funciones

### ISSUE THREAD

**Issue by evolentini** [germanCardozoE/testingDeSoftwareEmbebido#5]
La idea no es definir una función para preguntar si numero de led es válido, la idea es que devolver un error si yo trato de prender el led 17. Para esto es necesario definir como se van a gestionar los errores en el driver: puede ser llamando a una función de callback que registre los errores en un log y que se defina al crear la librería (junto con el puerto) o un valor de retorno en las funciones.

https://github.com/germanCardozoE/testingDeSoftwareEmbebido/blob/0edc6d1971e93a1f7cec83fb072484a5e6803c3f/TP_ceedling/leds/src/leds.c#L44-L49

**Comment by evolentini** [comment]
Ahora hay código que controla que los parámetros estén en limites validos pero no hay pruebas que justifiquen ese código, por lo tanto no se aplicó correctamente la metodología de TDD

**Comment by germanCardozoE** [comment]
Hola Esteban.
Creo que interprete mal la corrección inicial de este punto.
En definitiva entiendo que lo que debí hacer era una función para controlar
los límites, testearla y luego usarla en las otras funciones.
Por favor cuando puedas aclarame esta duda.

Saludos
Germán Eloy Cardozo

**Comment by evolentini** [comment]
German, la metodología de desarrollo propuesta dice que todo el código que se escribe es para resolver una prueba que no funciona. Lo que debías hacer es pensar una o mas pruebas que utilicen las funciones con parámetros inválidos, y entonces recién agregar el código para resolver los problemas que aparezcan en las pruebas.
